### ISSUE TITLE
Bug with steam making offer

### ISSUE THREAD

**Issue by ThreadShakur** [bukson/steampy#21]
Don't delete this issue...
Well first makeoffer will return None, next will work correctly

**Comment by bukson** [comment]
Is it still an issue?

**Comment by ThreadShakur** [comment]
its warning for peaple

**Comment by bukson** [comment]
So its still happening?

**Comment by ThreadShakur** [comment]
yes

**Comment by Ermans** [comment]
Ok I think I found the problem.
When SteamClient makes the login request, 4 cookies are assigned to the domain "steamcommunity.com" but to send a tradeoffer a "sessionid" cookie is required too.

This is why the first request doesn't work because it miss a cookie, but after the failed request the "sessionid" cookie is set so the second request performs successfully.

I made a workaround simply doing a post request after the login to "steamcommunity.com"  without any data.

**Comment by bukson** [comment]
Nice, would you like to fix this and contribute(by setting cookie) or i should patch this?

**Comment by ThreadShakur** [comment]
And bukson, can you add to oficial relese make_offer_url?

**Comment by Ermans** [comment]
Pull request submitted

**Comment by bukson** [comment]
Ok i will add that also

**Comment by bukson** [comment]
Merged and pushed on pip.
