### ISSUE TITLE
How do I accept mobile trade confirmations?

### ISSUE THREAD

**Issue by Hitm0nLim** [bukson/steampy#210]
I need some help confirming trades that have been sent via Steam and not though steampy. I see that it can be done through `send_trade_allow_request()` but I cannot get the required `trade_offer_id` parameter from `get_trade_offers()`. How should I do this?

**Comment by Requestedd** [comment]
BUMP!

Please help solve this problem.
With accept_trade_offer, I can accept all trades that other users have sent me.
However, if I send the trade myself, then the accept_trade_offer method is not suitable to confirm it, instead, you need to use _confirm_transaction, and then everything will work out.

However, I still can't figure out how to get the trade_offer_id to enter in _confirm_transaction. I tried to monitor the network in the browser during the creation of the request, and when requesting "https://steamcommunity.com/tradeoffer/new/send", the answer is the same trade_offer_id that I need.

BUT QUESTION: Is it possible to get this trade_offer_id in another way without forming a trade? (Because the get_trade_offer method does not show the  trade_offer_id of the sent trade)

Related Topics:
https://github.com/bukson/steampy/issues/133
https://github.com/bukson/steampy/issues/153
https://github.com/bukson/steampy/issues/208

**Comment by bukson** [comment]
Fixed with #274
