### ISSUE TITLE
Confriming all listings awaiting confirmation on market

### ISSUE THREAD

**Issue by SPr3D** [bukson/steampy#276]
I am writing a telegram bot for myself to confirm exchanges, receive a code so as not to use SDA. It remains to do the last function to confirm all listings awaiting confirmation on market. 
Please tell me which SteamPY functions I need to use to implement my idea.

![Screenshot_1](https://github.com/bukson/steampy/assets/112720989/d2a331c3-60d7-4993-8f87-f5b478bad6a8)

**Comment by wolfovik** [comment]
This is fairly simple to do. You will only need two functions from the steampy/confirmation.py file.

Get a list of all offers from def _get_confirmations
In a loop for each offer, call def _send_confirmation.
You're all set.
Bear in mind, if you just start confirming all offers in a row, you might fall prey to scammers.
I did it differently. In my version, on the contrary, I cancel all offers that have not been confirmed within 24 hours. This is much safer and offers do not accumulate.

**Comment by SPr3D** [comment]
@wolfovik, thank you so much <3

**Comment by SPr3D** [comment]
@wolfovik
Am I doing something wrong? 
If I just call "executor", everything works fine, but as I call executor._get_confirmations() I get an error: 
"    response = self._session.get(self.CONF_URL + '/conf', params=params, headers=headers)
TypeError: get() missing 1 required positional argument: 'url'
"
![image](https://github.com/bukson/steampy/assets/112720989/95b2fc8d-b612-4342-9451-6d83ebbb0da4)
![image](https://github.com/bukson/steampy/assets/112720989/386f4e7e-ff28-4b15-889e-d8b80c758eb4)

**Comment by wolfovik** [comment]
@SPr3D 

It's possible that you didn't initialize the ConfirmationExecutor class, that's why there's no reference to CONF_URL. Also, Steam no longer supports requests to https://steamcommunity.com/mobileconf/conf. Instead, you need to use https://steamcommunity.com/mobileconf/conf/getlist.

Here's what the latest stable version looks like (at least on my end).
[https://github.com/wolfovik/steampy/blob/3b70ec036c94f6147ce49e2a765da6c0bcc85091/steampy/confirmation.py](https://github.com/wolfovik/steampy/blob/3b70ec036c94f6147ce49e2a765da6c0bcc85091/steampy/confirmation.py)

**Comment by SPr3D** [comment]
@wolfovik
Here https://github.com/wolfovik/steampy/blob/3b70ec036c94f6147ce49e2a765da6c0bcc85091/steampy/confirmation.py
still an old link without /getlist part, is it okay?

That's how I'm trying to initialize:

from steampy import confirmation

identity_secret = "ZV7AY***********="
steamid = "765611**********"
**executor** = confirmation.ConfirmationExecutor(identity_secret=identity_secret,my_steam_id=steamid,session=requests.Session)
#And then I am trying to use def _get_confirmations and in this part I am getting error, What am I doing wrong?
confirmation_list = **executor**._get_confirmations()

**Comment by SPr3D** [comment]
@wolfovik
I installed the latest stable version, which you send, but I steel have an error in line 71
response = self._session.get(self.CONF_URL + '/getlist', params=params, headers=headers)
TypeError: get() missing 1 required positional argument: 'url' 

executor = confirmation.ConfirmationExecutor(identity_secret=identity_secret,my_steam_id=steamid,session=requests.Session())
confirmation_list = executor._get_confirmations()

Should I upload something else to the session?

**Comment by wolfovik** [comment]
@SPr3D 
It's hard to say. Unfortunately, I can't test this on my computer because I have a custom SteamPy environment set up. Try doing this:

1. Add the confirmation function to the steampy/confirmation.py itself.

`def accept_all_conformations(self):
   accept_conformations_list = self._get_confirmations()
   //A filter for offers definitely needs to be here.
   for conformation in accept_conformations_list:
      self._send_confirmation(conformation)
   return 'Success'`

2. Before creating an instance of the ConfirmationExecutor class, make sure you're logged into Steam and that the session is alive(client.is_session_alive()).

3. After you've created an instance of the ConfirmationExecutor class with an active session, try calling accept_all_conformations().

I'd like to remind you once again, if you just start accepting all offers in a row, your items will be stolen. You need to set up a filter!

**Comment by Onione-Tamiko** [comment]
@SPr3D How's the progress?

**Comment by Anunah9** [comment]
> Here's what the latest stable version looks like (at least on my end). https://github.com/wolfovik/steampy/blob/3b70ec036c94f6147ce49e2a765da6c0bcc85091/steampy/confirmation.py

It works!!! thank you so much
