### ISSUE TITLE
create_buy_order  >> "There was a problem creating the order. Are you using the right currency? success: 8"

### ISSUE THREAD

**Issue by Slava-stack** [bukson/steampy#350]
```
line 160, in create_buy_order
    raise ApiException(
steampy.exceptions.ApiException: There was a problem creating the order. Are you using the right currency? success: 8
```
Error print from the response:
```
{'success': 8, 'message': 'Sorry! We had trouble hearing back from the Steam servers about your order. 
Double check whether or not your order has actually been created or filled. If not, then please try again later.'}
```

Is it related to the recent steam update?

**Comment by Aarab228** [comment]
Are you sure you sent the right team? Judging by the error code - 8: InvalidParam. Post your function here so I can try to help you!

***If you have cookie authorization working, please help me set it up!***

**Comment by Slava-stack** [comment]
> Are you sure you sent the right team? Judging by the error code - 8: InvalidParam. Post your function here so I can try to help you!
> 
> _**If you have cookie authorization working, please help me set it up!**_

I am not 100% sure about the code, but I've done that according to the documentation 
```
with SteamClient(api_key, username, password, steam_guard_path) as client:
    response = client.market.create_buy_order("AK-47 | Redline (Field-Tested)", "1000", 1, game, currency)
    buy_order_id = response.json()
    print(buy_order_id)
```
Unfortunately I don't have a cookie authrization solution :(

**Comment by Slava-stack** [comment]
I've changed my set_sessionid_cookies from your issue disscussion https://github.com/bukson/steampy/issues/351 it works once in a while but there are some errors like:
`No response received from Steam API. Please try again later.`
or 
`client_id = login_response.json()['response']['client_id'] 
KeyError: 'client_id'`
Because of empty login_response looking like:
`{'response': {'interval': 5, 'extended_error_message': ''}}`

**Comment by copriz** [comment]
Hi! 

Please help me, I don't understand why it doesn't work. I wrote the following code, but it doesn't work because of an error: **success: 8.** 

My code:
`from steampy.client import SteamClient 
from steampy.models import GameOptions, Currency

steam_client = SteamClient('api') 
steam_client.login('name', 'password', 'steam_guard.json') 

itemName = "Claddish Gauntlets"
response = steam_client.market.create_buy_order(itemName, "6", 1, GameOptions.DOTA2, Currency.USD)
buy_order_id = response["buy_orderid"]`

I added logging to the library and to the code, here is the result:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): steamcommunity.com:443
DEBUG:urllib3.connectionpool:https://steamcommunity.com:443 "POST / HTTP/1.1" 200 8577
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.steampowered.com:443
DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "GET /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=NAME HTTP/1.1" 200 597
DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "POST /IAuthenticationService/BeginAuthSessionViaCredentials/v1 HTTP/1.1" 200 701
DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "POST /IAuthenticationService/UpdateAuthSessionWithSteamGuardCode/v1 HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "POST /IAuthenticationService/PollAuthSessionStatus/v1 HTTP/1.1" 200 682
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.steampowered.com:443
DEBUG:urllib3.connectionpool:https://login.steampowered.com:443 "POST /jwt/finalizelogin HTTP/1.1" 200 877
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): store.steampowered.com:443
DEBUG:urllib3.connectionpool:https://store.steampowered.com:443 "POST /login/settoken HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:https://steamcommunity.com:443 "POST /login/settoken HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): help.steampowered.com:443
DEBUG:urllib3.connectionpool:https://help.steampowered.com:443 "POST /login/settoken HTTP/1.1" 200 12
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): checkout.steampowered.com:443
DEBUG:urllib3.connectionpool:https://checkout.steampowered.com:443 "POST /login/settoken HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): steam.tv:443
DEBUG:urllib3.connectionpool:https://steam.tv:443 "POST /login/settoken HTTP/1.1" 200 32
DEBUG:root:Trying to create buy order for item: Claddish Gauntlets
DEBUG:root:Sending request to create buy order...
DEBUG:urllib3.connectionpool:https://steamcommunity.com:443 "POST /market/createbuyorder/ HTTP/1.1" 200 170
DEBUG:root:API response: {'success': 8, 'message': 'Sorry! We had trouble hearing back from the Steam servers about your order. Double check whether or not your order has actually been created or filled. If not, then please try again later.'}
Traceback (most recent call last):
  File "c:\Users\Le\Desktop\Business\Code\STEAM scripts\Bots\Script_3_tests.py", line 19, in <module>
    response = steam_client.market.create_buy_order(itemName, "6", 1, GameOptions.DOTA2, Currency.USD)
  File "C:\Users\Le\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\utils.py", line 23, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\market.py", line 160, in create_buy_order
    raise ApiException(
steampy.exceptions.ApiException: There was a problem creating the order. Are you using the right currency? success: 8

**Comment by Aarab228** [comment]
> Hi! 
> 
> 
> 
> Please help me, I don't understand why it doesn't work. I wrote the following code, but it doesn't work because of an error: **success: 8.** 
> 
> 
> 
> My code:
> 
> `from steampy.client import SteamClient 
> 
> from steampy.models import GameOptions, Currency
> 
> 
> 
> steam_client = SteamClient('api') 
> 
> steam_client.login('name', 'password', 'steam_guard.json') 
> 
> 
> 
> itemName = "Claddish Gauntlets"
> 
> response = steam_client.market.create_buy_order(itemName, "6", 1, GameOptions.DOTA2, Currency.USD)
> 
> buy_order_id = response["buy_orderid"]`
> 
> 
> 
> I added logging to the library and to the code, here is the result:
> 
> 
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): steamcommunity.com:443
> 
> DEBUG:urllib3.connectionpool:https://steamcommunity.com:443 "POST / HTTP/1.1" 200 8577
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.steampowered.com:443
> 
> DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "GET /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=NAME HTTP/1.1" 200 597
> 
> DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "POST /IAuthenticationService/BeginAuthSessionViaCredentials/v1 HTTP/1.1" 200 701
> 
> DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "POST /IAuthenticationService/UpdateAuthSessionWithSteamGuardCode/v1 HTTP/1.1" 200 41
> 
> DEBUG:urllib3.connectionpool:https://api.steampowered.com:443 "POST /IAuthenticationService/PollAuthSessionStatus/v1 HTTP/1.1" 200 682
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.steampowered.com:443
> 
> DEBUG:urllib3.connectionpool:https://login.steampowered.com:443 "POST /jwt/finalizelogin HTTP/1.1" 200 877
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): store.steampowered.com:443
> 
> DEBUG:urllib3.connectionpool:https://store.steampowered.com:443 "POST /login/settoken HTTP/1.1" 200 32
> 
> DEBUG:urllib3.connectionpool:https://steamcommunity.com:443 "POST /login/settoken HTTP/1.1" 200 32
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): help.steampowered.com:443
> 
> DEBUG:urllib3.connectionpool:https://help.steampowered.com:443 "POST /login/settoken HTTP/1.1" 200 12
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): checkout.steampowered.com:443
> 
> DEBUG:urllib3.connectionpool:https://checkout.steampowered.com:443 "POST /login/settoken HTTP/1.1" 200 32
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): steam.tv:443
> 
> DEBUG:urllib3.connectionpool:https://steam.tv:443 "POST /login/settoken HTTP/1.1" 200 32
> 
> DEBUG:root:Trying to create buy order for item: Claddish Gauntlets
> 
> DEBUG:root:Sending request to create buy order...
> 
> DEBUG:urllib3.connectionpool:https://steamcommunity.com:443 "POST /market/createbuyorder/ HTTP/1.1" 200 170
> 
> DEBUG:root:API response: {'success': 8, 'message': 'Sorry! We had trouble hearing back from the Steam servers about your order. Double check whether or not your order has actually been created or filled. If not, then please try again later.'}
> 
> Traceback (most recent call last):
> 
>   File "c:\Users\Le\Desktop\Business\Code\STEAM scripts\Bots\Script_3_tests.py", line 19, in <module>
> 
>     response = steam_client.market.create_buy_order(itemName, "6", 1, GameOptions.DOTA2, Currency.USD)
> 
>   File "C:\Users\Le\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\utils.py", line 23, in func_wrapper
> 
>     return func(self, *args, **kwargs)
> 
>   File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\market.py", line 160, in create_buy_order
> 
>     raise ApiException(
> 
> steampy.exceptions.ApiException: There was a problem creating the order. Are you using the right currency? success: 8
> 
> 


are you sure, you wrote GameOptions right? Try to buy item  not at 0.06, buy to set => 0.1

**Comment by copriz** [comment]
it helped to remove the error with the number 8, but now the error with the number 2;(  (There was a problem creating the order. Are you using the right currency? success: 2). Does this function work for you?

**Comment by Aarab228** [comment]
> it helped to remove the error with the number 8, but now the error with the number 2;( (There was a problem creating the order. Are you using the right currency? success: 2). Does this function work for you?

Succes: 2 mean "General Failure.
Returned when a more specific error code cannot be determined. Analogous to HTTP 500." 

Try not to specify the currency parameter at all and show the answer after this manipulation

**Comment by Slava-stack** [comment]
> it helped to remove the error with the number 8, but now the error with the number 2;( (There was a problem creating the order. Are you using the right currency? success: 2). Does this function work for you?

Yeah it works but in my case not great as I thought.

**Comment by copriz** [comment]
can you please share the working code of the script exactly the part where you create a purchase request? I have now tried with a ruble account, but I can't ((( I tried dollars, tenge and rubles. 

if I delete the currency at all here: response = steam_client.market.create_buy_order(itemName, "5", 1, GameOptions.CS, Currency[here])

the following error is shown to me: Traceback (most recent call last):
  File "c:\Users\Leonid\Desktop\Business\Code\STEAM scripts\Bots\Script_1.py", line 8, in <module>
    response = steam_client.market.create_buy_order(itemName, "5", 1, GameOptions.CS, Currency)
  File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\utils.py", line 23, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\market.py", line 143, in create_buy_order
    'currency': currency.value,
  File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\enum.py", line 405, in __getattr__
    raise AttributeError(name) from None
AttributeError: value

**Comment by Aarab228** [comment]
> can you please share the working code of the script exactly the part where you create a purchase request? I have now tried with a ruble account, but I can't ((( I tried dollars, tenge and rubles.
> 
> if I delete the currency at all here: response = steam_client.market.create_buy_order(itemName, "5", 1, GameOptions.CS, Currency[here])
> 
> the following error is shown to me: Traceback (most recent call last): File "c:\Users\Leonid\Desktop\Business\Code\STEAM scripts\Bots\Script_1.py", line 8, in response = steam_client.market.create_buy_order(itemName, "5", 1, GameOptions.CS, Currency) File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\utils.py", line 23, in func_wrapper return func(self, *args, **kwargs) File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\market.py", line 143, in create_buy_order 'currency': currency.value, File "C:\Users\Leonid\AppData\Local\Programs\Python\Python39\lib\enum.py", line 405, in **getattr** raise AttributeError(name) from None AttributeError: value


I took the query from the example in the documentation only changing currency to RUB
```python
order_query = self.client.market.create_buy_order("AK-47 | Redline (Field-Tested)", "10", 2, GameOptions.CS, Currency.RUB) 
    buy_order_id = response["buy_orderid"]
``` 
10 - that 0.10 RUB or 0.0011 USD

**Comment by copriz** [comment]
thank you very much! Can you also share the lines of code where you set the response and self functions?

**Comment by Aarab228** [comment]
> thank you very much! Can you also share the lines of code where you set the response and self functions?

At this point, I've pretty much destroyed the code because cookie authorization doesn't work. And to use self, just use a class object and initialize it
```python
class Bot(QMainWindow):
    def __init__(self):
        super(Bot, self).__init__()
        self.client = SteamClient(steam_API_KEY)
        self.ui = Ui_MainWindow()
```

**Comment by copriz** [comment]
thanks)))
